#version 430

layout (local_size_x = 32, local_size_y = 32, local_size_z = 1) in;
layout(binding = 0, rgba8ui) writeonly uniform uimage2D texture;

void main() {
    ivec2 threadIndex = ivec2(gl_GlobalInvocationID.xy);
    // Pixels from same workgroup will have same color
    uvec4 color = uvec4(vec2(gl_WorkGroupID.xy) / vec2(gl_NumWorkGroups.xy) * 255, 0, 255);
    imageStore(texture, threadIndex, color);
}